name: Deploy to AKS

on:
  #workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Images to Azure Container Registry"]
    types:
      - completed
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set AKS context
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         cluster-name: votingtest
         resource-group: voting-app
         
      - name: test 
        run: az account list --all --output table         

      - name: Configure kubectl
        run: az aks install-cli
        
      - name:  Configure kubectl2
        run: az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure kubectl
        run: az aks get-credentials --resource-group voting-app --name votingtest

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s-specifications
