name: Deploy to AKS

on:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
         cluster-name: votingtest
         resource-group: voting-app

      - name: Configure kubectl
        run: az aks install-cli

      - name: Configure kubectl
        run: az aks get-credentials --resource-group voting-app --name votingtest

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s-specifications
